### ISSUE TITLE
Enable the option for not encoding the images

### ISSUE THREAD

**Issue by Almeida-a** [Almeida-a/imodec-dicoogle-plugin#14]
If the `<codec>` tag of the settings xml file is empty or non-existent, don't encode dicom objects upon storing.

**Comment by Almeida-a** [comment]
This is a breaking change, and now that I think about it is not that much crucial for now, because once #15 is done, one can simply losslessly encode the image in order to keep a 100% fidelity.

**Comment by Enet4** [comment]
Please consider the possibility of configuring the plugin to encode and save the same file in multiple transfer syntaxes, including in native form. While redundant, this would prepare the PACS archive for providing data in these transfer syntaxes quickly.

**Comment by Almeida-a** [comment]
Keeping the pixel-data in native form is now allowed - 6d0fd5c.
I finished the feature of allowing to encode with all formats -- native and modern formats - 874eb72.
Then, I updated http request structure, adding new parameters in order to select and view the different (de)coded images - 58aeff7.
The readme description of that structure is updated as well - 791b9b1.

**Comment by Almeida-a** [comment]
The pull request is ready to be carried out.
Will close this issue afterwards.
